# Generated by Django 3.0.7 on 2020-06-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gubun', models.CharField(max_length=30)),
                ('code', models.TextField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabun', models.IntegerField()),
                ('join_day', models.CharField(default='', max_length=20)),
                ('retire_day', models.CharField(default='', max_length=20)),
                ('put_yn', models.CharField(default='', max_length=2)),
                ('name', models.CharField(default='', max_length=20)),
                ('reg_no', models.CharField(default='', max_length=20)),
                ('eng_name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('hp', models.CharField(default='', max_length=20)),
                ('carrier', models.CharField(default='', max_length=100)),
                ('pos_gbn_code', models.CharField(default='', max_length=10)),
                ('cmp_reg_no', models.CharField(default='', max_length=100)),
                ('sex', models.CharField(default='', max_length=10)),
                ('years', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=30)),
                ('zip', models.CharField(default='', max_length=20)),
                ('addr1', models.CharField(default='', max_length=100)),
                ('addr2', models.CharField(default='', max_length=100)),
                ('dept_code', models.CharField(default='', max_length=20)),
                ('join_gbn_code', models.CharField(default='', max_length=30)),
                ('user_id', models.CharField(default='', max_length=20)),
                ('pwd', models.CharField(default='', max_length=30)),
                ('salary', models.IntegerField(default=0)),
                ('kosa_reg_yn', models.CharField(default='', max_length=4)),
                ('kosa_class_code', models.CharField(default='', max_length=10)),
                ('mil_yn', models.CharField(default='', max_length=4)),
                ('mil_type', models.CharField(default='', max_length=20)),
                ('mil_level', models.CharField(default='', max_length=20)),
                ('mil_startdate', models.CharField(default='', max_length=20)),
                ('mil_enddate', models.CharField(default='', max_length=20)),
                ('job_type', models.CharField(default='', max_length=20)),
                ('gart_level', models.CharField(default='', max_length=20)),
                ('self_intro', models.CharField(default='', max_length=100)),
                ('crm_name', models.CharField(default='', max_length=20)),
                ('profile', models.CharField(default='', max_length=100)),
                ('cmp_reg_image', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
