# Generated by Django 3.0.7 on 2020-06-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='upload_files/%Y%m%d/')),
                ('file_name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(db_column='profile', default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cmp_reg_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='upload_files/%Y%m%d/')),
                ('file_name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('cmp_reg_image', models.ForeignKey(db_column='cmp_reg_image', default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='upload_files/%Y%m%d/')),
                ('file_name', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(db_column='carrier', default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.User')),
            ],
        ),
    ]
