# Generated by Django 3.0.7 on 2020-06-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carrier_cmp_reg_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='cmp_reg_image',
            name='cmp_reg_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AlterField(
            model_name='user',
            name='carrier',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cmp_reg_image',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
