# Generated by Django 3.0.7 on 2020-06-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200629_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilea',
            name='file_path',
            field=models.FileField(upload_to='upload_files/'),
        ),
    ]
